### ISSUE TITLE
Create Page Header

### ISSUE THREAD

**Issue by razzlepdx** [Web-Bakers/web-bakers#3]
For all Web Bakers pages

**Comment by reuben-jones** [comment]
Checklist:
- Add/remove items to nav
-- Logo (Ideas), Ideas, Projects, [Login, Sign up] / Member dropdown
-- Member dropdown = Settings, Profile?, Help?, Logout   
- Link up nav items
- Top border color?
- Active state for nav items

**Comment by reuben-jones** [comment]
Done: 
- Add/remove items to nav
-- Logo (Ideas), Ideas, Projects, [Login, Sign up] / Member dropdown
-- Member dropdown = Settings, Profile?, Help?, Logout
- Link up nav items

**Comment by reuben-jones** [comment]
Done: 
- Active state for nav items

**Comment by reuben-jones** [comment]
- ~~Top border color?~~
