### ISSUE TITLE
write project setup instructions

### ISSUE THREAD

**Issue by razzlepdx** [Web-Bakers/web-bakers#32]

**Comment by razzlepdx** [comment]
Project setup should have 2 sections:
- for new contributors to set up their dev environment
- for existing contributors to get the app running

**Comment by razzlepdx** [comment]
resolved by #47

**Comment by jsjoeio** [comment]
Hey @razzlepdx - what if we added this to the [Wiki](https://github.com/Web-Bakers/web-bakers/wiki)?
