### ISSUE TITLE
Create Web Bakers Logo(s)

### ISSUE THREAD

**Issue by razzlepdx** [Web-Bakers/web-bakers#4]

**Comment by razzlepdx** [comment]
Send Brainstorming ideas to Joe!

**Comment by razzlepdx** [comment]
Baked item, chef hat, etc.  Mixing Bowl, kitchen utensils, egg beaters, whisk.

**Comment by jsjoeio** [comment]
![screen shot 2017-07-31 at 5 21 37 pm](https://user-images.githubusercontent.com/3806031/28803951-f125fb88-7614-11e7-8799-10bd0c7f2012.png)


Playing around with this design. And this font: [Lobster](https://fonts.google.com/specimen/Lobster?selection.family=Lobster)
