### ISSUE TITLE
Add navigation between /register and /login

### ISSUE THREAD

**Issue by razzlepdx** [Web-Bakers/web-bakers#43]
Currently a user cannot navigate between signup and login except via the menu at the top of the page.  

Since the user will be auto-redirected to /signin if they attempt to add an idea anonymously, I think adding buttons between the pages would be helpful.

/register should have a button with text explaining: "Already registered?  Sign in here"
/signup should have a button with text: "Don't have a login yet?  Register here"

**Comment by jsjoeio** [comment]
@razzlepdx  This is a great point you bring up! 

Where do you imagine we add these in? the navbar (header) or somewhere on each individual page that is somewhat consistent.

**Comment by razzlepdx** [comment]
What do you think about adding these in small text either just above the form on both pages, or under the submit button?  I think those are the two places where I would normally look for that option.

**Comment by reuben-jones** [comment]
Yah, in this kind of situation I find that it's usually best to model design after the big guys—regardless of what might be the "best" place to display it, people will be trained to look for it somewhere specific. Eg:

![image](https://user-images.githubusercontent.com/1831818/32900029-56d68066-caa1-11e7-9965-df979233ed23.png)

![image](https://user-images.githubusercontent.com/1831818/32900117-8e1bffec-caa1-11e7-80e3-d16273002118.png)

![image](https://user-images.githubusercontent.com/1831818/32900207-cede91ca-caa1-11e7-89a3-a12b75eb10dc.png)

![image](https://user-images.githubusercontent.com/1831818/32900264-f114487a-caa1-11e7-903f-e7e131318dba.png)

![image](https://user-images.githubusercontent.com/1831818/32900314-0e232a58-caa2-11e7-8aab-78547ce14f07.png)

![image](https://user-images.githubusercontent.com/1831818/32900364-242549da-caa2-11e7-8bf4-dc438adbdad6.png)

**Comment by reuben-jones** [comment]
Generally: Very close to (following) the login/signup button.

**Comment by jsjoeio** [comment]
Now I understand what you're referring to! Yes, this makes perfect sense. Thanks for all the examples @mrreubenjones !
