### ISSUE TITLE
Write contributing instructions

### ISSUE THREAD

**Issue by razzlepdx** [Web-Bakers/web-bakers#48]
Write up our contributing workflow, including the following steps:

- select/open an issue, assign yourself to that issue
- create new branch `issues/34-hide-buttons`
- fix issue
- submit PR - make sure to describe changes and set the base branch to develop, not master 
- after at least one approval, merge into `develop`
- once merged, close issue

**Comment by jsjoeio** [comment]
We should add this to the [Wiki](https://github.com/Web-Bakers/web-bakers/wiki)

**Comment by razzlepdx** [comment]
Resolved by #50
